import { create } from "zustand";

const useStore = create((set) => ({
  createPopUo: false,
  contactPopUp: false,
  contactInfo: { contact: "", name: "", type: "" },
  newContact: {},
  showPopUpWithContacts: false,
  contacts: [],
  contactId: "",
  vendorId: "",
  showPopUp: false,
  userCreatePopUp: false,
  userEditPopUp: false,
  isPricelist: false,
  pricelist: [],
  isProfile: false,
  is1C: false,
  rowIndex: 0,
  setRowIndex: (val) => set({ rowIndex: val }),
  setIs1C: (val) => set({ is1C: val }),
  setIsProfile: (val) => set({ isProfile: val }),
  setPricelist: (val) => set({ pricelist: val }),
  setIsPricelist: (val) => set({ isPricelist: val }),
  setVendorId: (val) => set({ vendorId: val }),
  setShowPopUp: (val) => set({ showPopUp: val }),
  setContacts: (val) => set({ contacts: val }),
  setContactId: (val) => set({ contactId: val }),
  setCreatePopUp: (val) => set({ createPopUp: val }),
  setContactPopUp: (val) => set({ contactPopUp: val }),
  setContactInfo: (val) => set({ contactInfo: val }),
  setNewcontact: (val) => set({ newcontact: val }),
  setUserCreatePopUp: (val) => set({ userCreatePopUp: val }),
  setUserEditPopUp: (val) => set({ userEditPopUp: val }),
  setShowPopUpWithContacts: (val) => set({ showPopUpWithContacts: val }),
  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
  // removeAllBears: () => set({ bears: 0 }),
  // updateBears: (newBears) => set({ bears: newBears }),
}));

export default useStore;
